# Generated by Django 5.1.1 on 2024-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='Body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='Created_at',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
